name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::888577059433:role/Deploy-Static-Website-to-S3
          aws-region: ap-south-1

      - name: Deploy files to S3
        run: |
          aws s3 sync ./my-static-website-s3 s3://gfg-static --delete

      - name: Invalidate CloudFront Cache (Optional)
        run: |
          aws cloudfront create-invalidation --distribution-id E1U84R8N8JPSN3 --paths "/*"
